### ISSUE TITLE
Логи ответа пс

### ISSUE THREAD

**Issue by Igor-Yworld** [mihdan/mihdan-index-now#11]
Здравствуйте.
К разговору в топике про логи. Не знаю как они будут у вас организованы. Но как предложение, отслеживать не более 10 минут после получения ответа 200. Иначе будет очень существенный лог.
По моим тестам, если пс отвечает и обходит отправленный урл, то это происходит в течении 10-15 минут. Если не приходит за это время, то уже и не придет или это произойдет штатно  при обходе сайта.

**Comment by mihdan** [comment]
Добавил время жизни лого и включение отедльных разделов для логгирования

![image](https://user-images.githubusercontent.com/666732/148663789-9e25301c-b689-48bb-9ced-0ae763548e27.png)
