### ISSUE TITLE
Коды ошибок 200+ - не ошибки

### ISSUE THREAD

**Issue by mihdan** [mihdan/mihdan-index-now#21]

**Comment by Igor-Yworld** [comment]
Здравствуйте.
С крайними обновлениями ответ от яндекса, с любой периодичностью отправки - 202
Понимаю, что это не ошибка, но и запрос вроде как не обрабатывается в итоге.

**Comment by leskei217** [comment]
у меня то же самое: код ответа 202

**Comment by mihdan** [comment]
https://developer.mozilla.org/ru/docs/Web/HTTP/Status/202

**Comment by mihdan** [comment]
202 | Accepted | "Принято". Запрос принят, но ещё не обработан. Не поддерживаемо, т.е., нет способа с помощью HTTP отправить асинхронный ответ позже, который будет показывать итог обработки запроса. Это предназначено для случаев, когда запрос обрабатывается другим процессом или сервером, либо для пакетной обработки.
-- | -- | --

**Comment by Igor-Yworld** [comment]
> 202	Accepted	"Принято". Запрос принят, но ещё не обработан. Не поддерживаемо, т.е., нет способа с помощью HTTP отправить асинхронный ответ позже, который будет показывать итог обработки запроса. Это предназначено для случаев, когда запрос обрабатывается другим процессом или сервером, либо для пакетной обработки.

Такое ощущение, что теперь яндекс не справляется с количеством запросов или ждет сигнала от другой пс.

**Comment by kaikash** [comment]
Яндекс возвращает 202, когда запрос приняли, но ключ еще не проверен. После того как яндекс проверит ключ, он начнет возвращать 200, если с ключом все ок.

**Comment by kaikash** [comment]
> Здравствуйте. С крайними обновлениями ответ от яндекса, с любой периодичностью отправки - 202 Понимаю, что это не ошибка, но и запрос вроде как не обрабатывается в итоге.

В итоге, если с ключом все ок, то он обработается после того, как роботы яндекса загрузят и проверят ключ.
