### ISSUE TITLE
Ping to all search engines

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [mihdan/mihdan-index-now#29]
Why not making search engines being a checkbox instead of a radio, and thus allow pinging to several search engines?

[X] Yandex
[X] Bing
[X] DuckDuckGo

**Comment by mihdan** [comment]
Search Engines adopting the IndexNow protocol agree that submitted URLs will be automatically shared with all other participating Search Engines. To participate, search engines must have a noticeable presence in at least one market.

**Comment by javiergutierrezchamorro** [comment]
Thank you so much for your clarifications.
